services:
  dev-service-rag:
    build:
      context: .
      dockerfile: Dockerfile
    image: rag-app:latest
    container_name: dev-service-rag
    working_dir: /app
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONPATH: "/app/src"
      DATABASE_URL: ${DATABASE_URL_DOCKER}
    volumes:
      - .:/app:cached
    ports:
      - "8000:8000"
    command: >
      sh -c "python -m rag api"
    restart: no

volumes:
  pip-cache:
  python-site-packages:
