services:
  # PostgreSQL + pgvector 数据库
  rag-db:
    image: pgvector/pgvector:pg18
    container_name: rag-db
    ports:
      - "5434:5432"
    env_file:
      - .env
    volumes:
      - rag-postgres-data:/var/lib/postgresql

volumes:
  rag-postgres-data:
